<html>
<body>
Исключения, выброшенные с помощью оператора <code>throw</code>, всегда могут быть перехвачены включающим их оператором <code>try</code>.
<p>Использование оператора <code>throw</code> в качестве "goto" для изменения локального потока управления может вызвать путаницу и привести к снижению производительности.
<p><b>Пример:</b></p>
<pre><code>
  try {
    if (!Files.isDirectory(PROJECTS)) {
        throw new IllegalStateException("Directory not found."); // Предупреждение: 'throw' перехватывается включающим оператором 'try'
    }
    ...
  } catch (Exception e) {
      LOG.error("run failed");
  }
</code></pre>
<p>Используйте опцию <b>игнорировать повторно выброшенные исключения</b>, чтобы пропускать повторно выброшенные исключения.</p>
</body>
</html>
